version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis:Z

  gitlab:
    restart: always
    image: sameersbn/gitlab:9.5.5
    depends_on:
    - redis
    ports:
    - "10080:80"
    - "10022:22"
    volumes:
    - /srv/docker/gitlab/git/data:/home/git/data:Z
    environment:
    - DEBUG=false

    - DB_ADAPTER=$DB_ADAPTER
    - DB_HOST=$DB_HOST
    - DB_PORT=$DB_PORT
    - DB_USER=$DB_USER
    - DB_PASS=$DB_PASS
    - DB_NAME=$DB_NAME

    - REDIS_HOST=$REDIS_HOST
    - REDIS_PORT=$REDIS_PORT

    - LDAP_ENABLED=$LDAP_ENABLED
    - LDAP_LABEL=$LDAP_LABEL
    - LDAP_HOST=$LDAP_HOST
    - LDAP_PORT=$LDAP_PORT
    - LDAP_UID =$LDAP_UID
    - LDAP_METHOD=$LDAP_METHOD
    - LDAP_BIND_DN=$LDAP_BIND_DN
    - LDAP_PASS=$LDAP_PASS
    - LDAP_TIMEOUT=$LDAP_TIMEOUT
    - LDAP_BASE=$LDAP_BASE
    - LDAP_USER_FILTER=$LDAP_USER_FILTER

    - LDAP_ACTIVE_DIRECTORY=$LDAP_ACTIVE_DIRECTORY
    - LDAP_ALLOW_USERNAME_OR_EMAIL_LOGIN=$LDAP_ALLOW_USERNAME_OR_EMAIL_LOGIN
    - LDAP_BLOCK_AUTO_CREATED_USERS=$LDAP_BLOCK_AUTO_CREATED_USERS

    - GITLAB_REPOS_DIR=$GITLAB_REPOS_DIR
    - GITLAB_BACKUP_DIR=$GITLAB_BACKUP_DIR
    - GITLAB_BUILDS_DIR=$GITLAB_BUILDS_DIR
    - GITLAB_DOWNLOADS_DIR=$GITLAB_DOWNLOADS_DIR
    - GITLAB_SHARED_DIR=$GITLAB_SHARED_DIR

    - GITLAB_SIGNUP_ENABLED=$GITLAB_SIGNUP_ENABLED
    - GITLAB_CREATE_GROUP=$GITLAB_CREATE_GROUP
    - GITLAB_USERNAME_CHANGE=$GITLAB_USERNAME_CHANGE
    - GITLAB_PROJECTS_WIKI=$GITLAB_PROJECTS_WIKI
    - GITLAB_PROJECTS_CONTAINER_REGISTRY=$GITLAB_PROJECTS_CONTAINER_REGISTRY

    - TZ=$TZ
    - GITLAB_TIMEZONE=$GITLAB_TIMEZONE

    - GITLAB_HTTPS=$GITLAB_HTTPS

    - GITLAB_HOST=$GITLAB_HOST
    - GITLAB_PORT=$GITLAB_PORT
    - GITLAB_SSH_PORT=$GITLAB_SSH_PORT
    - GITLAB_RELATIVE_URL_ROOT=$GITLAB_RELATIVE_URL_ROOT
    - GITLAB_SECRETS_DB_KEY_BASE=$GITLAB_SECRETS_DB_KEY_BASE
    - GITLAB_SECRETS_SECRET_KEY_BASE=$GITLAB_SECRETS_SECRET_KEY_BASE
    - GITLAB_SECRETS_OTP_KEY_BASE=$GITLAB_SECRETS_OTP_KEY_BASE

    - GITLAB_ROOT_PASSWORD=$GITLAB_ROOT_PASSWORD
    - GITLAB_ROOT_EMAIL=$GITLAB_ROOT_EMAIL

    - GITLAB_EMAIL=$GITLAB_EMAIL

    - GITLAB_BACKUP_SCHEDULE=$GITLAB_BACKUP_SCHEDULE
    - GITLAB_BACKUP_TIME=$GITLAB_BACKUP_TIME

    - NGINX_WORKERS=$NGINX_WORKERS
    - NGINX_X_FORWARDED_PROTO=$NGINX_X_FORWARDED_PROTO
    - NGINX_REAL_IP_RECURSIVE=$NGINX_REAL_IP_RECURSIVE

    - SMTP_ENABLED=$SMTP_ENABLED
    - IMAP_ENABLED=$IMAP_ENABLED
  labels:
    aliyun.probe.url: tcp://container:80
    aliyun.probe.initial_delay_seconds: "10"
    aliyun.routing.port_80: git;git.$GIT_DOMAIN
    aliyun.lb.port_22: tcp://slb_docker_cluster_1_gitlab:10022