phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    labels:
      aliyun.probe.url: tcp://container:80
      aliyun.probe.initial_delay_seconds: "10"
      aliyun.routing.port_80: ldap